name: Scan Project with VirusTotal

on:
  push:
    branches: [ "main" ] # اگر شاخه اصلی master است بگذار master

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # زیپ کردن اتوماتیک فایل‌ها
      - name: Compress project
        run: zip -r my-project.zip . -x "*.git*" ".github*"

      # اسکن فایل زیپ‌شده
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v5
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          files: |
            ./my-project.zip
