name: Scan with VirusTotal

on:
  push:
    branches: [ "main" ] # برای تست با هر Push اجرا می‌شود
  release:
    types: [published]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      # ۱. دریافت کدهای پروژه
      - name: Checkout repository
        uses: actions/checkout@v4

      # ۲. اجرای اسکن با ابزار رسمی VirusTotal
      - name: Scan file with VirusTotal
        uses: virustotal/vt-cli-action@v1
        with:
          api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          files: |
            ./*.zip # <-- اینجا اسم دقیق فایل یا پوشه‌ای که می‌خواهی اسکن شود را بنویس
