name: Scan Project with VirusTotal

on:
  push:
    branches: [ "main" ] # اگر اسم شاخه‌ات master است، اینجا بگذار master

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # زیپ کردن خودکار تمام فایل‌های پروژه
      - name: Compress project
        run: zip -r project-scan.zip . -x "*.git*" ".github*"

      # فرستادن زیپ به ویروس‌توتال
      - name: Scan with VirusTotal
        uses: virustotal/vt-cli-action@v1
        with:
          api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          files: ./*.zip
